random_proxies = ['https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt',
                  'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/blob/master/socks4.txt',
                  'https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt',
                  'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt',
                  'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt',
                  'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt',
                  'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt',
                  'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt',
                  'https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt',
                  'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt',
                  'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt',
                  'https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txt',
                  'https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4',
                  'https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5',
                  'https://api.proxyscrape.com/v2/?request=getproxies&protocol=https',
                  'https://api.proxyscrape.com/v2/?request=getproxies&protocol=http',
                  'https://www.proxy-list.download/api/v1/get?type=socks4',
                  'https://proxy-spider.com/api/proxies.example.txt',
                  'https://www.proxyscan.io/download?type=socks4',
                  'https://www.proxyscan.io/download?type=socks5',
                  'https://www.proxyscan.io/download?type=https',
                  'https://www.proxyscan.io/download?type=http',
                  'https://multiproxy.org/txt_all/proxy.txt',
                  'http://rootjazz.com/proxies/proxies.txt',
                  'http://ab57.ru/downloads/proxyold.txt']

http_proxies = ['https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt',
                'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt',
                'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt',
                'https://api.proxyscrape.com/v2/?request=getproxies&protocol=https',
                'https://api.proxyscrape.com/v2/?request=getproxies&protocol=http',
                'https://www.proxyscan.io/download?type=https',
                'https://www.proxyscan.io/download?type=http']

socks_proxies = ['https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt',
                 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt',
                 'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt',
                 'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt',
                 'https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt',
                 'https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4',
                 'https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5',
                 'https://www.proxy-list.download/api/v1/get?type=socks4',
                 'https://www.proxyscan.io/download?type=socks4',
                 'https://www.proxyscan.io/download?type=socks5']
